name: Run Oshime Bot

on:
  # 手動実行（任意）
  workflow_dispatch:
    inputs:
      force:
        description: "強制実行（取引時間チェック無視）"
        type: boolean
        default: false
  # スケジュール実行（UTC基準）
  # JST 9:02–15:32 を 30分おき（混雑回避の2分/32分）
  schedule:
    - cron: '2,32 0-6 * * 1-5'

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: oshime-bot
      cancel-in-progress: true   # ← 古い実行をキャンセルして最新のみ実行

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'                                # ← pip キャッシュ
          cache-dependency-path: '**/requirements.txt'

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install deps
        run: pip install -r requirements.txt          # ← 固定バージョンで安定

      - name: Check envs
        run: |
          test -n "${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}" || (echo "Missing LINE_CHANNEL_ACCESS_TOKEN" && exit 1)
          test -n "${{ secrets.LINE_USER_ID }}" || (echo "Missing LINE_USER_ID" && exit 1)

      - name: Run python
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
          # 手動実行時のみ force=1 に
          FORCE_RUN: ${{ github.event_name == 'workflow_dispatch' && inputs.force && '1' || '' }}
        run: python main.py
